config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/' => 'events#mainpage'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :events

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.


    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [ :mainpage, :show, :index ]


  def mainpage
    respond_to do |format|
      format.html { render :mainpage }
    end
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @user = @event.user_id

    if (current_user.id != @user)
      redirect_to "/events"

    end

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event , notice: 'Event was successfully created.'}
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :title, :description, :location, :latitude, :longitude, :imgURL, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
	<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date, class:'font-weight-bold' %>
    <br/>
    <%= form.text_field :date, class:'text-center w-50'%>
  </div>

  <div class="field">
    <%= form.label :title,class:'font-weight-bold' %>
    <br/>
    <%= form.text_field :title, class:'text-center w-50' %>
  </div>

  <div class="field">
    <%= form.label :description,class:'font-weight-bold' %>
    <br/>
    <%= form.text_area :description, class:'text-center w-50' %>
  </div>

  <div class="field">
    <%= form.label :location,class:'font-weight-bold' %>
    <br/>
    <%= form.text_field :location, class:'text-center w-50' %>
  </div>

  <div class="field">
    <%= form.label :latitude,class:'font-weight-bold' %>
    <br/>
    <%= form.text_field :latitude, class:'text-center w-50' %>
  </div>

  <div class="field">
    <%= form.label :longitude,class:'font-weight-bold' %>
    <br/>
    <%= form.text_field :longitude, class:'text-center w-50' %>
  </div>

  <div class="field">
    <%= form.label :imgURL,class:'font-weight-bold' %>
    <br/>
    <%= form.text_area :imgURL, class:'text-center w-50' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container position-absolute card bg-light my-3 "
style="left: 50%; text-align: center; transform: translate(-50%,0); max-width: 40rem;">

	<h1 class="my-4">Edit Events</h1>

	<%= render 'form', event: @event %>

	<%= link_to 'Back', events_path, class:'mb-3' %>

</div>

app/views/events/index.html.erb
<div class="container">

	<p id="notice"><%= notice %></p>

	<h1 class="text-center">Events</h1>

	<div style="display: flex; flex-wrap: wrap; justify-content: space-between;">
    <% @events.each do |event| %>
    	<div class="card mb-4" style="width: 18rem">
    		<img style="height: 200px;" class="card-img-top" alt="..." src=<%= event.imgURL %> />
    		<div class="card-body">
	      	<h3 class="card-title"><%= event.title %></h3>
	      	<h5 class="card-title"><%= event.date.strftime("%A, %d %b %y, %H:%M%p") %></h5>
	      	<h5 class="card-title font-weight-light mb-3"><%= event.location %></h5>
	      	<p class="card-text mb-4"><%= event.description %></p>
	      	<p class="card-text">Hosted by: <%= event.user.name %></p>
	     	</div>
	      	<div class="card-footer">
	      		<%= link_to 'Show', event %>

		      	<% if user_signed_in? %>
		        	<% if current_user.id == event.user.id%>
		        		| <%= link_to 'Edit', edit_event_path(event) %> |
		        		<%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
		        	<% end %>
		  			<% end %>
		  		</div>
	  	</div>
    <% end %>
	</div>

</div>

app/views/events/mainpage.html.erb
<%= javascript_pack_tag 'app' %>

app/views/events/new.html.erb
<div class="container position-absolute card bg-light my-3"
style="left: 50%; text-align: center; transform: translate(-50%,0); max-width: 40rem;">

<h1 class="my-4">New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class:'mb-3'%>

</div>

app/views/events/show.html.erb
<div class="container">

	<p id="notice" style="width: 45rem; margin: 0 auto"><%= notice %></p>

	<div class="jumbotron" style="width: 45rem; margin: 0 auto">
		 <img class="card-img-top" src=<%= @event.imgURL %> >

	  <h1 class="display-4"><%= @event.title %></h1>
	  <p class="lead"><%= @event.date.strftime("%A, %d %b %y, %H:%M%p")  %></p>
	  <p class="lead"><%= @event.location %></p>
	  <hr class="my-4">
	  <p class="lead"><%= @event.description %></p>
	  <p class="lead">Hosted By: <%= @event.user.name%></p>
		<br/>
		<% if user_signed_in? && current_user.id == @event.user_id %>

			<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-light" %>

		<% end %>

		<%= link_to 'Back', events_path, class: "btn btn-light" %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenJio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
  	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #D73964;">
  		<a class="navbar-brand text-white" href="/">OpenJio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>

  		<div class="collapse navbar-collapse" id="navbarSupportedContent">
    		<ul class="navbar-nav mr-auto">
      		<li class="nav-item">
        		<a class="nav-link text-white" href="/">Home<span class="sr-only">(current)</span></a>
      		</li>
      		<li class="nav-item">
        		<a class="nav-link text-white" href="/events">Events Around You</a>
      		</li>
      		<li class="nav-item">
        		<a class="nav-link text-white" href="/events/new">Create New Event</a>
      		</li>

	    	</ul>
	    	<form class="form-inline my-2 my-lg-0 text-white">
      		<% if user_signed_in? %>
						<%= link_to 'Log Out', destroy_user_session_url, method: :delete , style:'color:white'%>
						<% else %>
						<%= link_to 'Log In', new_user_session_url, style:'color:white'%>
					<% end %>
    		</form>
	  	</div>
		</nav>

    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>


</html>